// <auto-generated />
using System;
using AggronomyProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggronomyProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AggronomyProject.Models.Administracion", b =>
                {
                    b.Property<int>("IdAdministracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_inventario")
                        .HasColumnType("int");

                    b.Property<int>("id_metodo_pago")
                        .HasColumnType("int");

                    b.Property<int>("id_recursos_administrador")
                        .HasColumnType("int");

                    b.Property<int>("id_reporte")
                        .HasColumnType("int");

                    b.Property<int>("id_trabajador")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAdministracion");

                    b.HasIndex("id_inventario");

                    b.HasIndex("id_metodo_pago");

                    b.HasIndex("id_recursos_administrador");

                    b.HasIndex("id_reporte");

                    b.HasIndex("id_trabajador");

                    b.ToTable("Administraciones");

                    b.HasData(
                        new
                        {
                            IdAdministracion = 1,
                            descripcion = "Registro inicial del sistema",
                            estado = true,
                            fecha_registro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_inventario = 1,
                            id_metodo_pago = 1,
                            id_recursos_administrador = 1,
                            id_reporte = 1,
                            id_trabajador = 1,
                            nombre = "Administración General",
                            responsable = "Sistema"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Inventario", b =>
                {
                    b.Property<int>("id_iventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_producto_final")
                        .HasColumnType("int");

                    b.Property<int>("id_producto_inicial")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_minimo")
                        .HasColumnType("int");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_iventario");

                    b.HasIndex("id_producto_final");

                    b.HasIndex("id_producto_inicial");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            id_iventario = 1,
                            descripcion = "Inventario inicial del sistema",
                            estado = true,
                            fecha_actualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_producto_final = 1,
                            id_producto_inicial = 1,
                            nombre = "Inventario General",
                            stock_actual = 0,
                            stock_minimo = 0,
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("id_pago")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdMetodoPago");

                    b.HasIndex("id_pago");

                    b.ToTable("MetodosPagos");

                    b.HasData(
                        new
                        {
                            IdMetodoPago = 1,
                            descripcion = "Pago en efectivo",
                            estado = true,
                            id_pago = 1,
                            nombre = "Efectivo"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_pago")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            IdPago = 1,
                            comprobante = "COMP-0001",
                            concepto = "Pago inicial",
                            estado = true,
                            fecha_pago = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 0.00m
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.ProductoFinal", b =>
                {
                    b.Property<int>("id_producto_final")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cantidad_producida")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<float>("precio_venta")
                        .HasColumnType("float");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_producto_final");

                    b.ToTable("ProductosFinales");

                    b.HasData(
                        new
                        {
                            id_producto_final = 1,
                            cantidad_producida = 0,
                            descripcion = "Producto de prueba",
                            estado = true,
                            nombre = "Producto Final Demo",
                            precio_venta = 0f,
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.ProductoInicial", b =>
                {
                    b.Property<int>("id_producto_inicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cantidad_inicial")
                        .HasColumnType("int");

                    b.Property<float>("costo_unitario")
                        .HasColumnType("float");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("proveedor_origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_producto_inicial");

                    b.ToTable("ProductosIniciales");

                    b.HasData(
                        new
                        {
                            id_producto_inicial = 1,
                            cantidad_inicial = 0,
                            costo_unitario = 0f,
                            descripcion = "Producto de prueba",
                            estado = true,
                            fecha_ingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Producto Inicial Demo",
                            proveedor_origen = "Demo",
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Proveedor", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_proveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            id_proveedor = 1,
                            direccion = "Sin dirección",
                            email = "proveedor@demo.com",
                            estado = true,
                            nombre = "Proveedor Demo",
                            ruc = "00000000000",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Recurso", b =>
                {
                    b.Property<int>("id_recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cantidad_recibida")
                        .HasColumnType("int");

                    b.Property<float>("costo_recurso")
                        .HasColumnType("float");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("tipo_recurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_recurso");

                    b.HasIndex("id_proveedor");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            id_recurso = 1,
                            cantidad_recibida = 0,
                            costo_recurso = 0f,
                            estado = true,
                            fecha_ingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_proveedor = 1,
                            tipo_recurso = "General",
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.RecursosAdministrador", b =>
                {
                    b.Property<int>("id_recursos_administrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("cantidad_recibida")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_recepcion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_recurso")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id_recursos_administrador");

                    b.HasIndex("id_recurso");

                    b.ToTable("RecursosAdministradores");

                    b.HasData(
                        new
                        {
                            id_recursos_administrador = 1,
                            cantidad_recibida = 0,
                            estado = true,
                            fecha_recepcion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_recurso = 1,
                            observaciones = "Registro inicial"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Reporte", b =>
                {
                    b.Property<int>("id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_generacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("generado_por")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo_reporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_reporte");

                    b.ToTable("Reportes");

                    b.HasData(
                        new
                        {
                            id_reporte = 1,
                            contenido = "Reporte generado por el sistema",
                            estado = true,
                            fecha_generacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            generado_por = "Sistema",
                            tipo_reporte = "General",
                            titulo = "Reporte Inicial"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Estado = true,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Estado = true,
                            NombreRol = "Trabajador"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Trabajador", b =>
                {
                    b.Property<int>("id_trabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("fecha_contrato")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id_trabajador");

                    b.ToTable("Trabajadores");

                    b.HasData(
                        new
                        {
                            id_trabajador = 1,
                            apellidos = "Demo",
                            cargo = "General",
                            dni = "00000000",
                            email = "trabajador@agronomia.com",
                            estado = true,
                            fecha_contrato = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombres = "Trabajador",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("AggronomyProject.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("RolIdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("RolIdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "Admin123",
                            CorreoElectronico = "admin@agronomia.com",
                            Estado = true,
                            IdRol = 1,
                            NombreUsuario = "admin"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Contrasena = "Trab123",
                            CorreoElectronico = "trabajador@agronomia.com",
                            Estado = true,
                            IdRol = 2,
                            NombreUsuario = "trabajador"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AggronomyProject.Models.Administracion", b =>
                {
                    b.HasOne("AggronomyProject.Models.Inventario", "inventario")
                        .WithMany("administracion")
                        .HasForeignKey("id_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.MetodoPago", "metodopago")
                        .WithMany("administracion")
                        .HasForeignKey("id_metodo_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.RecursosAdministrador", "recursosadministrador")
                        .WithMany()
                        .HasForeignKey("id_recursos_administrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.Reporte", "reporte")
                        .WithMany("administracion")
                        .HasForeignKey("id_reporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.Trabajador", "trabajador")
                        .WithMany("administracion")
                        .HasForeignKey("id_trabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventario");

                    b.Navigation("metodopago");

                    b.Navigation("recursosadministrador");

                    b.Navigation("reporte");

                    b.Navigation("trabajador");
                });

            modelBuilder.Entity("AggronomyProject.Models.Inventario", b =>
                {
                    b.HasOne("AggronomyProject.Models.ProductoFinal", "productofinal")
                        .WithMany("inventario")
                        .HasForeignKey("id_producto_final")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.ProductoInicial", "productoinicial")
                        .WithMany("inventario")
                        .HasForeignKey("id_producto_inicial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productofinal");

                    b.Navigation("productoinicial");
                });

            modelBuilder.Entity("AggronomyProject.Models.MetodoPago", b =>
                {
                    b.HasOne("AggronomyProject.Models.Pago", "pago")
                        .WithMany("metodopago")
                        .HasForeignKey("id_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pago");
                });

            modelBuilder.Entity("AggronomyProject.Models.Recurso", b =>
                {
                    b.HasOne("AggronomyProject.Models.Proveedor", "proveedor")
                        .WithMany("recurso")
                        .HasForeignKey("id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("AggronomyProject.Models.RecursosAdministrador", b =>
                {
                    b.HasOne("AggronomyProject.Models.Recurso", "recurso")
                        .WithMany("recursosadministrador")
                        .HasForeignKey("id_recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recurso");
                });

            modelBuilder.Entity("AggronomyProject.Models.Usuario", b =>
                {
                    b.HasOne("AggronomyProject.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AggronomyProject.Models.Rol", null)
                        .WithMany("Usuario")
                        .HasForeignKey("RolIdRol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AggronomyProject.Models.Inventario", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("AggronomyProject.Models.MetodoPago", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("AggronomyProject.Models.Pago", b =>
                {
                    b.Navigation("metodopago");
                });

            modelBuilder.Entity("AggronomyProject.Models.ProductoFinal", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("AggronomyProject.Models.ProductoInicial", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("AggronomyProject.Models.Proveedor", b =>
                {
                    b.Navigation("recurso");
                });

            modelBuilder.Entity("AggronomyProject.Models.Recurso", b =>
                {
                    b.Navigation("recursosadministrador");
                });

            modelBuilder.Entity("AggronomyProject.Models.Reporte", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("AggronomyProject.Models.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AggronomyProject.Models.Trabajador", b =>
                {
                    b.Navigation("administracion");
                });
#pragma warning restore 612, 618
        }
    }
}
