// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAgroEspinosa_2026.Data;

#nullable disable

namespace ProyectoAgroEspinosa_2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917202730_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", b =>
                {
                    b.Property<int>("id_recursos_administrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_recursos_administrador"));

                    b.Property<int>("cantidad_recibida")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_recepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_recurso")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_recursos_administrador");

                    b.HasIndex("id_recurso");

                    b.ToTable("RecursosAdministradores");

                    b.HasData(
                        new
                        {
                            id_recursos_administrador = 1,
                            cantidad_recibida = 0,
                            estado = true,
                            fecha_recepcion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_recurso = 1,
                            observaciones = "Registro inicial"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Inventario", b =>
                {
                    b.Property<int>("id_iventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_iventario"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_producto_final")
                        .HasColumnType("int");

                    b.Property<int>("id_producto_inicial")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("stock_actual")
                        .HasColumnType("int");

                    b.Property<int>("stock_minimo")
                        .HasColumnType("int");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_iventario");

                    b.HasIndex("id_producto_final");

                    b.HasIndex("id_producto_inicial");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            id_iventario = 1,
                            descripcion = "Inventario inicial del sistema",
                            estado = true,
                            fecha_actualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_producto_final = 1,
                            id_producto_inicial = 1,
                            nombre = "Inventario General",
                            stock_actual = 0,
                            stock_minimo = 0,
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_UserTT", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("U_RoleCCIdRol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.HasIndex("U_RoleCCIdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "Admin123",
                            CorreoElectronico = "admin@agronomia.com",
                            Estado = true,
                            IdRol = 1,
                            NombreUsuario = "admin"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Contrasena = "Trab123",
                            CorreoElectronico = "trabajador@agronomia.com",
                            Estado = true,
                            IdRol = 2,
                            NombreUsuario = "trabajador"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("id_pago")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMetodoPago");

                    b.HasIndex("id_pago");

                    b.ToTable("MetodosPagos");

                    b.HasData(
                        new
                        {
                            IdMetodoPago = 1,
                            descripcion = "Pago en efectivo",
                            estado = true,
                            id_pago = 1,
                            nombre = "Efectivo"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("comprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_pago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            IdPago = 1,
                            comprobante = "COMP-0001",
                            concepto = "Pago inicial",
                            estado = true,
                            fecha_pago = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 0.00m
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.ProductoFinal", b =>
                {
                    b.Property<int>("id_producto_final")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_producto_final"));

                    b.Property<int>("cantidad_producida")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("precio_venta")
                        .HasColumnType("real");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_producto_final");

                    b.ToTable("ProductosFinales");

                    b.HasData(
                        new
                        {
                            id_producto_final = 1,
                            cantidad_producida = 0,
                            descripcion = "Producto de prueba",
                            estado = true,
                            nombre = "Producto Final Demo",
                            precio_venta = 0f,
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.ProductoInicial", b =>
                {
                    b.Property<int>("id_producto_inicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_producto_inicial"));

                    b.Property<int>("cantidad_inicial")
                        .HasColumnType("int");

                    b.Property<float>("costo_unitario")
                        .HasColumnType("real");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("proveedor_origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_producto_inicial");

                    b.ToTable("ProductosIniciales");

                    b.HasData(
                        new
                        {
                            id_producto_inicial = 1,
                            cantidad_inicial = 0,
                            costo_unitario = 0f,
                            descripcion = "Producto de prueba",
                            estado = true,
                            fecha_ingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Producto Inicial Demo",
                            proveedor_origen = "Demo",
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Proveedor", b =>
                {
                    b.Property<int>("id_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_proveedor"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_proveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            id_proveedor = 1,
                            direccion = "Sin dirección",
                            email = "proveedor@demo.com",
                            estado = true,
                            nombre = "Proveedor Demo",
                            ruc = "00000000000",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.Property<int>("id_recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_recurso"));

                    b.Property<int>("cantidad_recibida")
                        .HasColumnType("int");

                    b.Property<float>("costo_recurso")
                        .HasColumnType("real");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_proveedor")
                        .HasColumnType("int");

                    b.Property<string>("tipo_recurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("unidad_medida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_recurso");

                    b.HasIndex("id_proveedor");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            id_recurso = 1,
                            cantidad_recibida = 0,
                            costo_recurso = 0f,
                            estado = true,
                            fecha_ingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_proveedor = 1,
                            tipo_recurso = "General",
                            unidad_medida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Reporte", b =>
                {
                    b.Property<int>("id_reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_reporte"));

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_generacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("generado_por")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tipo_reporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_reporte");

                    b.ToTable("Reportes");

                    b.HasData(
                        new
                        {
                            id_reporte = 1,
                            contenido = "Reporte generado por el sistema",
                            estado = true,
                            fecha_generacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            generado_por = "Sistema",
                            tipo_reporte = "General",
                            titulo = "Reporte Inicial"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.T_AdmTT", b =>
                {
                    b.Property<int>("IdAdministracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdministracion"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_inventario")
                        .HasColumnType("int");

                    b.Property<int>("id_metodo_pago")
                        .HasColumnType("int");

                    b.Property<int>("id_recursos_administrador")
                        .HasColumnType("int");

                    b.Property<int>("id_reporte")
                        .HasColumnType("int");

                    b.Property<int>("id_trabajador")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAdministracion");

                    b.HasIndex("id_inventario");

                    b.HasIndex("id_metodo_pago");

                    b.HasIndex("id_recursos_administrador");

                    b.HasIndex("id_reporte");

                    b.HasIndex("id_trabajador");

                    b.ToTable("Administraciones");

                    b.HasData(
                        new
                        {
                            IdAdministracion = 1,
                            descripcion = "Registro inicial del sistema",
                            estado = true,
                            fecha_registro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            id_inventario = 1,
                            id_metodo_pago = 1,
                            id_recursos_administrador = 1,
                            id_reporte = 1,
                            id_trabajador = 1,
                            nombre = "Administración General",
                            responsable = "Sistema"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Trabajador", b =>
                {
                    b.Property<int>("id_trabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_trabajador"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_contrato")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_trabajador");

                    b.ToTable("Trabajadores");

                    b.HasData(
                        new
                        {
                            id_trabajador = 1,
                            apellidos = "Demo",
                            cargo = "General",
                            dni = "00000000",
                            email = "trabajador@agronomia.com",
                            estado = true,
                            fecha_contrato = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombres = "Trabajador",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.U_RoleCC", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("U_RoleCC");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Estado = true,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Estado = true,
                            NombreRol = "Trabajador"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.R_Resource", "recurso")
                        .WithMany("recursosadministrador")
                        .HasForeignKey("id_recurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recurso");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Inventario", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.ProductoFinal", "productofinal")
                        .WithMany("inventario")
                        .HasForeignKey("id_producto_final")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.ProductoInicial", "productoinicial")
                        .WithMany("inventario")
                        .HasForeignKey("id_producto_inicial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productofinal");

                    b.Navigation("productoinicial");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_UserTT", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.U_RoleCC", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.U_RoleCC", null)
                        .WithMany("Usuario")
                        .HasForeignKey("U_RoleCCIdRol");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.MetodoPago", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.Pago", "pago")
                        .WithMany("metodopago")
                        .HasForeignKey("id_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pago");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.Proveedor", "proveedor")
                        .WithMany("recurso")
                        .HasForeignKey("id_proveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.T_AdmTT", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.Inventario", "inventario")
                        .WithMany("administracion")
                        .HasForeignKey("id_inventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.MetodoPago", "metodopago")
                        .WithMany("administracion")
                        .HasForeignKey("id_metodo_pago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", "recursosadministrador")
                        .WithMany()
                        .HasForeignKey("id_recursos_administrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.Reporte", "reporte")
                        .WithMany("administracion")
                        .HasForeignKey("id_reporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.Trabajador", "trabajador")
                        .WithMany("administracion")
                        .HasForeignKey("id_trabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventario");

                    b.Navigation("metodopago");

                    b.Navigation("recursosadministrador");

                    b.Navigation("reporte");

                    b.Navigation("trabajador");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Inventario", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.MetodoPago", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Pago", b =>
                {
                    b.Navigation("metodopago");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.ProductoFinal", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.ProductoInicial", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Proveedor", b =>
                {
                    b.Navigation("recurso");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.Navigation("recursosadministrador");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Reporte", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.Trabajador", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.U_RoleCC", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
