// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoAgroEspinosa_2026.Data;

#nullable disable

namespace ProyectoAgroEspinosa_2026.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921205752_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", b =>
                {
                    b.Property<int>("idRecursosAdministrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecursosAdministrador"));

                    b.Property<int>("cantidadrecibida")
                        .HasColumnType("int");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecharecepcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idRecurso")
                        .HasColumnType("int");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idRecursosAdministrador");

                    b.HasIndex("idRecurso");

                    b.ToTable("RecursosAdministradores");

                    b.HasData(
                        new
                        {
                            idRecursosAdministrador = 1,
                            cantidadrecibida = 0,
                            estado = true,
                            fecharecepcion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idRecurso = 1,
                            observaciones = "Registro inicial"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.E_Final_Product", b =>
                {
                    b.Property<int>("idProductoFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProductoFinal"));

                    b.Property<int>("cantidadproducida")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("precioventa")
                        .HasColumnType("real");

                    b.Property<string>("unidadmedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idProductoFinal");

                    b.ToTable("ProductosFinales");

                    b.HasData(
                        new
                        {
                            idProductoFinal = 1,
                            cantidadproducida = 0,
                            descripcion = "Producto de prueba",
                            estado = true,
                            nombre = "Producto Final Demo",
                            precioventa = 0f,
                            unidadmedida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.E_Initial_Product", b =>
                {
                    b.Property<int>("idProductoInicial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProductoInicial"));

                    b.Property<int>("cantidadinicial")
                        .HasColumnType("int");

                    b.Property<float>("costounitario")
                        .HasColumnType("real");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaingreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("proveedororigen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("unidadmedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idProductoInicial");

                    b.ToTable("ProductosIniciales");

                    b.HasData(
                        new
                        {
                            idProductoInicial = 1,
                            cantidadinicial = 0,
                            costounitario = 0f,
                            descripcion = "Producto de prueba",
                            estado = true,
                            fechaingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombre = "Producto Inicial Demo",
                            proveedororigen = "Demo",
                            unidadmedida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.F_Paid", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("int");

                    b.Property<string>("comprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechapago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            IdPago = 1,
                            IdMetodoPago = 1,
                            comprobante = "COMP-0001",
                            concepto = "Pago inicial",
                            estado = true,
                            fechapago = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            monto = 0.00m
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.G_Report", b =>
                {
                    b.Property<int>("idReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idReporte"));

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechageneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("generadopor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tiporeporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("idReporte");

                    b.ToTable("Reportes");

                    b.HasData(
                        new
                        {
                            idReporte = 1,
                            contenido = "Reporte generado por el sistema",
                            estado = true,
                            fechageneracion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            generadopor = "Sistema",
                            tiporeporte = "General",
                            titulo = "Reporte Inicial"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.K_Worker", b =>
                {
                    b.Property<int>("idTrabajador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idTrabajador"));

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("cargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechacontrato")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idTrabajador");

                    b.ToTable("Trabajadores");

                    b.HasData(
                        new
                        {
                            idTrabajador = 1,
                            apellidos = "Demo",
                            cargo = "General",
                            dni = "00000000",
                            email = "trabajador@agronomia.com",
                            estado = true,
                            fechacontrato = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            nombres = "Trabajador",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.L_Inventory", b =>
                {
                    b.Property<int>("idInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idInventario"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaactualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idProductoFinal")
                        .HasColumnType("int");

                    b.Property<int>("idProductoInicial")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("stockactual")
                        .HasColumnType("int");

                    b.Property<int>("stockminimo")
                        .HasColumnType("int");

                    b.Property<string>("unidadmedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idInventario");

                    b.HasIndex("idProductoFinal");

                    b.HasIndex("idProductoInicial");

                    b.ToTable("Inventarios");

                    b.HasData(
                        new
                        {
                            idInventario = 1,
                            descripcion = "Inventario inicial del sistema",
                            estado = true,
                            fechaactualizacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idProductoFinal = 1,
                            idProductoInicial = 1,
                            nombre = "Inventario General",
                            stockactual = 0,
                            stockminimo = 0,
                            unidadmedida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_Paymentmethod", b =>
                {
                    b.Property<int>("IdMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoPago"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMetodoPago");

                    b.ToTable("MetodosPagos");

                    b.HasData(
                        new
                        {
                            IdMetodoPago = 1,
                            descripcion = "Pago en efectivo",
                            estado = true,
                            nombre = "Efectivo"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_UserTT", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "Admin123",
                            CorreoElectronico = "admin@agronomia.com",
                            Estado = true,
                            IdRol = 1,
                            NombreUsuario = "admin"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Contrasena = "Trab123",
                            CorreoElectronico = "trabajador@agronomia.com",
                            Estado = true,
                            IdRol = 2,
                            NombreUsuario = "trabajador"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.P_Supplier", b =>
                {
                    b.Property<int>("idProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProveedor"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ruc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idProveedor");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            idProveedor = 1,
                            direccion = "Sin dirección",
                            email = "proveedor@demo.com",
                            estado = true,
                            nombre = "Proveedor Demo",
                            ruc = "00000000000",
                            telefono = "000000000"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.Property<int>("idRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecurso"));

                    b.Property<int>("cantidadrecibida")
                        .HasColumnType("int");

                    b.Property<float>("costorecurso")
                        .HasColumnType("real");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaingreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("idProveedor")
                        .HasColumnType("int");

                    b.Property<string>("tiporecurso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("unidadmedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("idRecurso");

                    b.HasIndex("idProveedor");

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            idRecurso = 1,
                            cantidadrecibida = 0,
                            costorecurso = 0f,
                            estado = true,
                            fechaingreso = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idProveedor = 1,
                            tiporecurso = "General",
                            unidadmedida = "kg"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.T_AdmTT", b =>
                {
                    b.Property<int>("IdAdministracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdministracion"));

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecharegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("idInventario")
                        .HasColumnType("int");

                    b.Property<int>("idRecursosAdministrador")
                        .HasColumnType("int");

                    b.Property<int>("idReporte")
                        .HasColumnType("int");

                    b.Property<int>("idTrabajador")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("responsable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAdministracion");

                    b.HasIndex("IdPago");

                    b.HasIndex("idInventario");

                    b.HasIndex("idRecursosAdministrador");

                    b.HasIndex("idReporte");

                    b.HasIndex("idTrabajador");

                    b.ToTable("Administraciones");

                    b.HasData(
                        new
                        {
                            IdAdministracion = 1,
                            IdPago = 1,
                            descripcion = "Registro inicial del sistema",
                            estado = true,
                            fecharegistro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            idInventario = 1,
                            idRecursosAdministrador = 1,
                            idReporte = 1,
                            idTrabajador = 1,
                            nombre = "Administración General",
                            responsable = "Sistema"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.U_RoleCC", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("U_RoleCC");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Estado = true,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Estado = true,
                            NombreRol = "Trabajador"
                        });
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.R_Resource", "recurso")
                        .WithMany("recursosadministrador")
                        .HasForeignKey("idRecurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recurso");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.F_Paid", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.M_Paymentmethod", "metodopago")
                        .WithMany("pagos")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("metodopago");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.L_Inventory", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.E_Final_Product", "productofinal")
                        .WithMany("inventario")
                        .HasForeignKey("idProductoFinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.E_Initial_Product", "productoinicial")
                        .WithMany("inventario")
                        .HasForeignKey("idProductoInicial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productofinal");

                    b.Navigation("productoinicial");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_UserTT", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.U_RoleCC", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.P_Supplier", "proveedor")
                        .WithMany("recurso")
                        .HasForeignKey("idProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("proveedor");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.T_AdmTT", b =>
                {
                    b.HasOne("ProyectoAgroEspinosa_2026.Models.F_Paid", "pago")
                        .WithMany("administracion")
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.L_Inventory", "inventario")
                        .WithMany("administracion")
                        .HasForeignKey("idInventario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.A_Resource_Adm", "recursosadministrador")
                        .WithMany()
                        .HasForeignKey("idRecursosAdministrador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.G_Report", "reporte")
                        .WithMany("administracion")
                        .HasForeignKey("idReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoAgroEspinosa_2026.Models.K_Worker", "trabajador")
                        .WithMany("administracion")
                        .HasForeignKey("idTrabajador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("inventario");

                    b.Navigation("pago");

                    b.Navigation("recursosadministrador");

                    b.Navigation("reporte");

                    b.Navigation("trabajador");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.E_Final_Product", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.E_Initial_Product", b =>
                {
                    b.Navigation("inventario");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.F_Paid", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.G_Report", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.K_Worker", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.L_Inventory", b =>
                {
                    b.Navigation("administracion");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.M_Paymentmethod", b =>
                {
                    b.Navigation("pagos");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.P_Supplier", b =>
                {
                    b.Navigation("recurso");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.R_Resource", b =>
                {
                    b.Navigation("recursosadministrador");
                });

            modelBuilder.Entity("ProyectoAgroEspinosa_2026.Models.U_RoleCC", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
